### ISSUE TITLE
Error on install - 'Requirement' object has no attribute 'project_name'

### ISSUE THREAD

**Issue by arjuntoor** [newmediadenver/evegenie#22]
I have just tried installing evegenie using the instructions on the homepage.  I cloned the repo into ~/git/evegenie, then ran the install command, but I immediately get an error.  Here is the overall console output:

```
arjun@arjun-G53SW:~/git/evegenie$ ll
total 32
drwxrwxr-x 2 arjun arjun 4096 Oct 10 20:51 docs/
drwxrwxr-x 3 arjun arjun 4096 Oct 10 20:51 evegenie/
-rw-rw-r-- 1 arjun arjun  736 Oct 10 20:51 geneve.py
-rw-rw-r-- 1 arjun arjun 1084 Oct 10 20:51 LICENSE
-rw-rw-r-- 1 arjun arjun 3371 Oct 10 20:51 README.md
-rw-rw-r-- 1 arjun arjun   37 Oct 10 20:51 requirements.txt
-rw-rw-r-- 1 arjun arjun  736 Oct 10 20:51 test.json
drwxrwxr-x 2 arjun arjun 4096 Oct 10 20:51 tests/
arjun@arjun-G53SW:~/git/evegenie$ sudo pip install -r requirements.txt
[sudo] password for arjun: 
The directory '/home/arjun/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/arjun/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in /home/arjun/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting pytest==2.7.2 (from -r requirements.txt (line 2))
  Downloading pytest-2.7.2-py2.py3-none-any.whl (127kB)
    100% |████████████████████████████████| 133kB 1.7MB/s 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'

```

Any ideas as to what could be causing this?

Interestingly, it does produce correct output when I run `python geneve.py test.json`

**Comment by ultimateboy** [comment]
Sorry for the slow response here @a12jun.

It looks like this is an issue with pip. See https://github.com/pypa/pip/issues/3687

Hopefully it's been resolved and you've been able to generate some schemas!

**Comment by cyberswat** [comment]
Closing due to inactivity. Please ensure it meets our [request guidelines](https://github.com/drud/community/blob/master/development/request_guidelines.md) if re-opened.
